name: Pyright Lint

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - "nonebot_plugin_kawaii_status/**"

jobs:
  pyright:
    name: Pyright Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python environment
        uses: ./.github/actions/setup-python

      - run: echo "$(pdm venv --path in-project)/bin" >> $GITHUB_PATH

      - name: Run Pyright
        uses: jakebailey/pyright-action@v2
